server:
  port: 8082

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test0706
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true  #设置开启热部署
      exclude: static/**
logging:
  level:
    root: INFO
